### ISSUE TITLE
Make `libm` dependency optional

### ISSUE THREAD

**Issue by juntyr** [ajtribick/twofloat#29]
The description of the `std` feature implies that it can be used to not rely on `libm`. However, `libm` is not an optional dependency.

If possible, I would suggest adding a `libm` feature to enable the now-optional `libm` dependency. If neither `std` or `libm` are enabled, a `std::compile_error` is emitted.

**Comment by ajtribick** [comment]
Thinking about this a bit, I'm leaning towards always using the libm version of the functions to avoid various issues with the C library implementations referenced by std (e.g. as already found in MinGW)

**Comment by juntyr** [comment]
Thank you for considering and explaining the decision!

**Comment by ajtribick** [comment]
Have updated everything to use libm, things are much more straightforward now and as a side effect managed to enable math_funcs in no_std mode. Going to close this issue as having done the complete opposite :)
