### ISSUE TITLE
no_fma mode?

### ISSUE THREAD

**Issue by ajtribick** [ajtribick/twofloat#4]
Might be useful to enable a mode that doesn't rely on FMA for multiplications. This might be necessary to address #3

**Comment by ChristopherRabotin** [comment]
There's an unpublished crate, `qd`, that uses a 2007 algorithm to implement double-double and quad-double. It supports `no_fma` as so: https://github.com/Barandis/qd/blob/737b45214c1a0c57ae469e9d8fa3b1ee296279db/src/common/primitive.rs#L24 . I hope this helps.

**Comment by ajtribick** [comment]
Addressed by using libm
