### ISSUE TITLE
add `num-traits` feature

### ISSUE THREAD

**Issue by joseluis** [ajtribick/twofloat#7]
It would be very nice to have optionally implemented [`num-traits`](https://crates.io/crates/num-traits) like ToPrimitive, FromPrimitive, Num, Float, FloatCore and Bounded, in a similar way as [what the `half` crate does](https://github.com/starkat99/half-rs/blob/main/src/num_traits.rs).

**Comment by ajtribick** [comment]
This is coming in the next version, currently on the v0.5-dev branch. I'm planning to release this after finishing off implementing the updated display functionality.

**Comment by joseluis** [comment]
I was going to test out the dev branch and I just realized it doesn't exist. Is that intended?

**Comment by ajtribick** [comment]
@joseluis - yes, I decided it wasn't particularly useful to have it split off. I've merged it into the main branch so you can use that instead.

**Comment by ajtribick** [comment]
I have now released this as v0.5.0, splitting off the incomplete string and macro functionality for a future release.
